; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
tickCount:
	DW	0
	ALIGN	2
resetHandler:
	; >>>>> Line:	8
	; >>>>> void resetHandler(){ 
	jmp	L_myinth_1
L_myinth_2:
	; >>>>> Line:	9
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_1:
	push	bp
	mov	bp, sp
	jmp	L_myinth_2
L_myinth_4:
	DB	"TICK ",0
	ALIGN	2
tickHandler:
	; >>>>> Line:	12
	; >>>>> void tickHandler(){ 
	jmp	L_myinth_5
L_myinth_6:
	; >>>>> Line:	13
	; >>>>> tickCount++; 
	inc	word [tickCount]
	; >>>>> Line:	14
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	15
	; >>>>> printString("TICK "); 
	mov	ax, L_myinth_4
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	16
	; >>>>> printUInt(tickCount); 
	push	word [tickCount]
	call	printUInt
	add	sp, 2
	; >>>>> Line:	17
	; >>>>> printNewLine(); 
	call	printNewLine
	mov	sp, bp
	pop	bp
	ret
L_myinth_5:
	push	bp
	mov	bp, sp
	jmp	L_myinth_6
L_myinth_11:
	DB	"DELAY COMPLETE",0
L_myinth_10:
	DB	"DELAY KEY PRESSED",0
L_myinth_9:
	DB	") IGNORED",0
L_myinth_8:
	DB	"KEYPRESS (",0
	ALIGN	2
keyHandler:
	; >>>>> Line:	19
	; >>>>> void keyHandler(){ 
	jmp	L_myinth_12
L_myinth_13:
	; >>>>> Line:	20
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	21
	; >>>>> if (KeyBuffer != 'd'){ 
	cmp	word [KeyBuffer], 100
	je	L_myinth_14
	; >>>>> Line:	22
	; >>>>> printString("KEYPRESS ("); 
	mov	ax, L_myinth_8
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	23
	; >>>>> printChar(KeyBuffer); 
	push	word [KeyBuffer]
	call	printChar
	add	sp, 2
	; >>>>> Line:	24
	; >>>>> printString(") IGNORED"); 
	mov	ax, L_myinth_9
	push	ax
	call	printString
	add	sp, 2
	jmp	L_myinth_15
L_myinth_14:
	; >>>>> Line:	26
	; >>>>> printString("DELAY KEY PRESSED"); 
	mov	ax, L_myinth_10
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	27
	; >>>>> delay = 0; 
	mov	word [delay], 0
	; >>>>> Line:	28
	; >>>>> while(delay < 5000) 
	jmp	L_myinth_17
L_myinth_16:
	; >>>>> Line:	29
	; >>>>> delay++; 
	inc	word [delay]
L_myinth_17:
	cmp	word [delay], 5000
	jb	L_myinth_16
L_myinth_18:
	; >>>>> Line:	30
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	31
	; >>>>> printString("DELAY COMPLETE"); 
	mov	ax, L_myinth_11
	push	ax
	call	printString
	add	sp, 2
L_myinth_15:
	; >>>>> Line:	33
	; >>>>> printNewLine(); 
	call	printNewLine
	mov	sp, bp
	pop	bp
	ret
L_myinth_12:
	push	bp
	mov	bp, sp
	jmp	L_myinth_13
	ALIGN	2
delay:
	TIMES	2 db 0
